[workspace]
resolver = "2"

[package]
name = "sobol_burley"
version = "0.7.0"
description = "A seedable Owen-scrambled Sobol sequence."
categories = ["algorithms", "mathematics", "no-std"]
keywords = [
    "sobol",
    "low-discrepancy",
    "monte-carlo",
    "quasirandom",
    "sampling",
]
documentation = "https://docs.rs/sobol_burley"
repository = "https://github.com/hayden4r4/sobol_burley"
readme = "README.md"
authors = [
    "Hayden Rose <hayden4r4@gmail.com>",
    "Nathan Vegdahl <cessen@cessen.com>",
]
edition = "2021"
license = "MIT OR Apache-2.0"
build = "build.rs"
exclude = ["/images"]

[features]
default = []
wgpu = ["dep:wgpu", "dep:futures-channel", "dep:pollster"]
wgpu-example = ["wgpu", "dep:bytemuck"]

[lib]
name = "sobol_burley"
path = "src/lib.rs"


[dependencies]
bytemuck = { version = "1.15", optional = true }
pollster = { version = "0.4", optional = true }
wgpu = { version = "27.0", optional = true }
futures-channel = { version = "0.3", optional = true }

[dev-dependencies]
rand = "0.9"
bencher = "0.1"
bytemuck = "1.15"
pollster = "0.4"


[profile.release]
lto = "fat"
codegen-units = 1

[[bench]]
name = "bench"
harness = false

[[example]]
name = "gpu_dispatch"
path = "examples/gpu_dispatch.rs"
required-features = ["wgpu-example"]
